version: '3'
services:
    front:
        image: nginx

        volumes:
            - ./php_for_nginx/conf/:/etc/nginx/conf.d
            - ./php/src/index.html:/usr/share/nginx/index.html
        ports:
            - "80:80"
        depends_on:
            - back

    back:

        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./php/src:/var/www/pr
            - ./php/000-default.conf:/etc/apache2/sites-available/000-default.conf
    db:

        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: appDB
        volumes:
            - ./:/docker-entrypoint-initdb.d
            - db_volume:/var/lib/mysql
        ports:
            - "3307:3306"
volumes:
    db_volume:
